// Isolated production browser storage only; never edits a player's save.
const assert = require('node:assert/strict')
const path = require('node:path')
const fs = require('node:fs/promises')
const { dismissReward } = require('./profile-qa.cjs')
const read = page => page.evaluate(() => JSON.parse(localStorage.getItem('muu-sinh-player-progress')).state)
const categories = [['TÓC',8],['ÁO',16],['QUẦN',10],['GIÀY',8],['PHỤ KIỆN',12],['ĐIỆN THOẠI',6],['ĐIỆN TỬ',8],['XE CỘ',9],['ĐỒ CÁ NHÂN',9],['NỘI THẤT',14]]

async function verifyLifestyleFlows(browser, origin, artifacts, assertLayout, baseState) {
  const context = await browser.newContext({ viewport:{width:390,height:844}, hasTouch:true, isMobile:true, acceptDownloads:true, timezoneId:'Asia/Ho_Chi_Minh' })
  const errors = []
  try {
    const page = await context.newPage()
    page.on('pageerror', error => errors.push(error.message))
    const dismissToasts = async () => {
      const close = page.getByRole('button',{name:'Đóng thông báo thành tựu',exact:true})
      for (let index = 0; index < 20 && await close.count(); index++) await close.click()
    }
    const fixture = { ...baseState, money:100_000_000, xp:900 }
    await page.addInitScript(state => {
      if (!localStorage.getItem('muu-sinh-player-progress')) localStorage.setItem('muu-sinh-player-progress',JSON.stringify({version:5,state}))
    },fixture)
    await page.goto(origin); await page.locator('.home-player').waitFor(); await dismissReward(page)
    await page.waitForFunction(() => !!navigator.serviceWorker.controller)
    const home = async () => page.getByRole('button',{name:'TRANG CHỦ',exact:true}).click()
    const shop = async () => { await home(); await page.getByRole('button',{name:'CỬA HÀNG',exact:true}).click() }
    await page.getByRole('button',{name:'CỬA HÀNG',exact:true}).click()
    for (const width of [360,390,412,1024]) {
      await page.setViewportSize({width,height:844})
      for (const [name,count] of categories) {
        await page.getByRole('tab',{name,exact:true}).click()
        assert.equal(await page.locator('.shop-item').count(),count)
        assert.equal(await page.locator('.item-preview svg').count(),count)
        await assertLayout(page,`Lifestyle ${name} ${width}`)
        const heights = await page.locator('.item-action').evaluateAll(nodes => nodes.map(n => n.getBoundingClientRect().height))
        assert.ok(heights.every(h => h >= 44),'Purchase touch target smaller than 44px')
      }
      await page.screenshot({path:path.join(artifacts,`lifestyle-shop-${width}.png`),fullPage:true,animations:'disabled'})
    }
    await page.setViewportSize({width:390,height:844})
    await page.getByRole('tab',{name:'XE CỘ',exact:true}).click()
    const premium = page.locator('[data-item-id="life-vehicle-premium"]')
    const before = await read(page)
    await premium.getByRole('button',{name:/Xem thử/}).click()
    assert.deepEqual(await read(page),before,'Preview persisted configuration')
    await premium.getByRole('button',{name:'MUA',exact:true}).click()
    await page.getByRole('dialog').getByRole('button',{name:'ĐỂ SAU',exact:true}).click()
    assert.deepEqual(await read(page),before,'Cancelled purchase spent money')
    const buyEquip = async (tab,id) => {
      await page.getByRole('tab',{name:tab,exact:true}).click()
      const card = page.locator(`[data-item-id="${id}"]`)
      const previous = await read(page)
      await card.getByRole('button',{name:'MUA',exact:true}).click()
      if (await page.getByRole('dialog').count()) await page.getByRole('dialog').getByRole('button',{name:'XÁC NHẬN MUA',exact:true}).click()
      const purchased = await read(page)
      assert.ok(purchased.money < previous.money && purchased.money >= 0)
      assert.equal(purchased.ownedItemIds.filter(item => item === id).length,1)
      await card.getByRole('button',{name:'TRANG BỊ',exact:true}).click()
      assert.equal((await read(page)).money,purchased.money,'Equip charged money')
    }
    for (const [tab,id] of [['TÓC','hair-braid'],['ÁO','shirt-hoodie'],['QUẦN','pants-shorts'],['GIÀY','life-shoes-sneakers'],['PHỤ KIỆN','life-accessory-bucket'],['PHỤ KIỆN','life-accessory-round'],['PHỤ KIỆN','life-accessory-daypack'],['ĐỒ CÁ NHÂN','life-tools-thermos']]) await buyEquip(tab,id)
    const dressed = await read(page)
    assert.equal(dressed.profile.appearance.shirtId,'hoodie')
    assert.equal(dressed.profile.lifestyle.equipment.hand,'life-tools-thermos')
    assert.ok(dressed.achievements.some(a => a.id === 'complete-outfit'))
    await home(); assert.equal(await page.locator('.home-player [data-equipment]').count(),5)
    await dismissToasts(); await page.screenshot({path:path.join(artifacts,'lifestyle-avatar.png'),fullPage:true,animations:'disabled'})
    await shop()
    await buyEquip('ĐIỆN THOẠI','life-phone-daily'); await buyEquip('ĐIỆN TỬ','life-electronics-laptop')
    await page.getByRole('button',{name:'THIẾT BỊ',exact:true}).click()
    await dismissToasts()
    assert.equal(await page.locator('.life-card').count(),2)
    await page.locator('[data-owned-item="life-phone-daily"]').getByText('✓ ĐANG DÙNG').waitFor()
    await page.screenshot({path:path.join(artifacts,'lifestyle-devices.png'),fullPage:true,animations:'disabled'})
    await shop()
    for (const id of ['life-vehicle-bike','life-vehicle-commuter','life-vehicle-scooter','life-vehicle-compact']) await buyEquip('XE CỘ',id)
    await page.getByRole('button',{name:'GARA',exact:true}).click()
    await dismissToasts()
    assert.equal(await page.locator('.life-card').count(),4)
    const balance = (await read(page)).money
    await page.locator('[data-owned-item="life-vehicle-scooter"]').getByRole('button',{name:'CHỌN DÙNG',exact:true}).click()
    assert.equal((await read(page)).profile.lifestyle.vehicle,'life-vehicle-scooter')
    assert.equal((await read(page)).money,balance)
    await page.screenshot({path:path.join(artifacts,'lifestyle-garage.png'),fullPage:true,animations:'disabled'})
    await page.getByRole('button',{name:'← HỒ SƠ',exact:true}).click()
    assert.equal(await page.locator('.profile-lifestyle > div').count(),3)
    await home(); await page.getByRole('button',{name:'KHÁM PHÁ THỊ TRẤN',exact:true}).click()
    await page.locator('.town-vehicle svg').waitFor()
    await shop()
    for (const id of ['life-home-cot','life-home-desk','life-home-chair','life-home-plant','life-home-lamp','life-home-picture']) await buyEquip('NỘI THẤT',id)
    await page.getByRole('button',{name:'PHÒNG CỦA TÔI',exact:true}).click()
    await dismissToasts()
    assert.equal(await page.locator('[data-room-slot]').count(),6)
    assert.equal(await page.locator('[data-room-phone]').count(),1)
    await page.getByLabel('Đặt Cây',{exact:true}).selectOption('')
    assert.equal((await read(page)).profile.lifestyle.room.plant,null)
    await page.getByLabel('Đặt Cây',{exact:true}).selectOption('life-home-plant')
    const decorated = await read(page)
    assert.ok(decorated.achievements.some(a => a.id === 'furnished-room'))
    assert.ok(decorated.achievements.some(a => a.id === 'first-smartphone'))
    assert.ok(decorated.achievements.some(a => a.id === 'first-vehicle'))
    for (const width of [360,390,412,1024]) {
      await page.setViewportSize({width,height:844}); await assertLayout(page,`Room ${width}`)
      await page.screenshot({path:path.join(artifacts,`lifestyle-room-${width}.png`),fullPage:true,animations:'disabled'})
    }
    await page.reload(); await page.locator('.home-player').waitFor(); await dismissReward(page)
    assert.deepEqual(await read(page),decorated,'Refresh changed lifestyle progress')
    await context.setOffline(true); await page.reload(); await page.locator('.home-player').waitFor(); await dismissReward(page)
    assert.deepEqual(await read(page),decorated)
    await page.getByRole('button',{name:'HỒ SƠ',exact:true}).click()
    await page.locator('.save-data-panel summary').click()
    const download = page.waitForEvent('download')
    await page.getByRole('button',{name:'TẢI FILE SAO LƯU',exact:true}).click()
    const backupPath = path.join(artifacts,'lifestyle-backup.json')
    await (await download).saveAs(backupPath)
    const backup = JSON.parse(await fs.readFile(backupPath,'utf8'))
    assert.equal(backup.version,5); assert.deepEqual(backup.data,decorated)
    await page.getByLabel('Chọn file sao lưu JSON').setInputFiles(backupPath)
    await page.getByRole('dialog').getByRole('button',{name:'KHÔI PHỤC',exact:true}).click()
    await page.locator('.home-player').waitFor(); await dismissReward(page)
    assert.deepEqual(await read(page),decorated)
    await page.getByRole('button',{name:'HỒ SƠ',exact:true}).click()
    await page.getByRole('button',{name:'PHÒNG CỦA TÔI',exact:true}).click()
    assert.equal(await page.locator('[data-room-slot]').count(),6)
    assert.deepEqual(errors,[])
    console.log('PASS: 100 illustrated products/10 categories, 360/390/412/1024 layouts, 44px touch targets, preview/cancel/buy/equip, five accessory slots, devices, four vehicle types, Town/Profile, fixed-slot room, shopping achievements, refresh/offline/v5 JSON restore')
  } finally { await context.close() }
}
module.exports = { verifyLifestyleFlows }
